#!/bin/bash

set -e
set -o pipefail

TMP="/tmp/__docker_container"

sudo docker container ls -a | \
awk 'NR>1 {print $0}' | \
fzf -0 | \
xargs -r | \
awk '{print $1}' | \
tee "$TMP" | \
awk '{print "Container: "$0}' && \
read -p "Are you sure?" && \
sudo docker container rm $(cat "$TMP")

