#!/bin/bash

set -e
set -o pipefail

TMP="/tmp/__docker_image"

sudo docker image ls -a | \
awk 'NR>1 {print $0}' | \
fzf -0 | \
xargs -r | \
awk '{print $1}' | \
tee "$TMP" | \
awk '{print "Image: "$0}' && \
read -p "Are you sure?" && \
sudo docker image stop $(cat "$TMP")

