#!/bin/bash
#
# Author: Joseph Hines
#
# 05/14/19
#

[[ $# -eq 1 ]] && printf "Converting...\n" || { printf "Please provide a single filename\n" > /dev/stderr && exit 1; };

[ -f "$1" ] || { printf "File '%s' does not exist\n" "$1" > /dev/stderr && exit 2; };

tr -d '\15\32' < "$1" > "$1".unix;
mv "$1".unix "$1";

printf "Conversion done!\n"
exit 0;
