#!/usr/bin/env python3

# Grade Letter Scale
A = 4
Aminus = 3.67
Bplus = 3.33
B = 3
Bminus = 2.67
Cplus = 2.33
C = 2
Cminus = 1.67
Dplus = 1.33
D = 1
Dminus = 0.67
F = 0

# Total before
quality_points = 526.35
credit_hours = 138

# Current term
current_credit_hours = 19
average_gpa = Bminus
current_quality_points = current_credit_hours * average_gpa

# New Cum
new_cum = (quality_points + current_quality_points) \
    / (credit_hours + current_credit_hours)
print(new_cum)

