#!/bin/bash

	pandocReady

	if [ -z "${1}" ]; then
		echo "You need to specify the markdown file"
		exit 0
	fi

	filename_without_ext=`rev <<< "${1}" | cut -d"." -f2- | rev`
  pdf_filename="${filename_without_ext}.pdf"

	pandoc -o "${pdf_filename}" -s "${1}"
