#!/bin/bash

	pandocReady

	if [ -z "${1}" ]; then
		echo "You need to specify the markdown file"
		exit 0
	fi

	filename_without_ext=`rev <<< "${1}" | cut -d"." -f2- | rev`
  pdf_filename="${filename_without_ext}-slides.pdf"



	pandoc -M slide_level=2 -o "${pdf_filename}" -t beamer "${1}" --template=$HOME/.doc_templates/beamer.latex
	#pandoc -M theme=Copenhagen -M colortheme=fly -M fontfamily=noto-sans -M slide_level=2 -o "${pdf_filename}" -t beamer "${1}"
