vim.opt.backupcopy="yes"
vim.opt.background="dark"
vim.opt.clipboard="unnamedplus"
vim.opt.colorcolumn="80"
vim.opt.encoding="utf-8"
vim.opt.errorbells = false
vim.opt.errorbells = true
vim.opt.expandtab = true
vim.opt.expandtab = true
vim.opt.guicursor = ""
vim.opt.hidden = true
vim.opt.hlsearch = false
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.incsearch = true
vim.opt.linebreak=true
vim.opt.list=true
vim.opt.listchars="tab:>-"
vim.opt.nrformats=""
vim.opt.number=true
vim.opt.relativenumber = true
vim.opt.scrolloff=8
vim.opt.shiftwidth=2
vim.opt.showmode = false
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop=2
vim.opt.swapfile = false
vim.opt.tabstop=2
vim.opt.termguicolors = false
vim.opt.undodir="/tmp/undos/$USER"
vim.opt.undofile = true
vim.opt.wildmenu = true
vim.opt.wrap=true
