#!/bin/bash
#

REPO_LOC=$HOME/repos/dotfiles

mkdir -p REPO_LOC

cp -v ~/.aliasrc $REPO_LOC/bash/
cp -v ~/.bashrc $REPO_LOC/bash/
cp -v ~/.inputrc $REPO_LOC/bash/
cp -v ~/.profile $REPO_LOC/bash/

cp -v ~/.config/nvim/* $REPO_LOC/vim/
cp -rv ~/.config/nvim/ultisnips $REPO_LOC/vim/
cp -rv ~/.config/nvim/templates $REPO_LOC/vim/

cp -rv ~/.local/bin/myscripts/* $REPO_LOC/scripts/

