#!/bin/bash

	require "convert"

	if [ -z "${1}" ]; then
		echo "You need to specify the markdown file"
		exit 0
	fi

	if [ -z "${2}" ]; then
		filename_without_ext=`rev <<< "${1}" | cut -d"." -f2- | rev`
	  pdf_filename="${filename_without_ext}"
	else
		pdf_filename="${2}"
	fi

	convert -quality 100 -density 600x600 "${pdf_filename}".pdf "${pdf_filename}"-%d.jpg
