#!/bin/bash
#

if (( "$#" == 1 )) ; then

	pamixer --list-sinks | awk 'NR>1 { print $1 }' | while read file; do
		pamixer --sink "$file" --allow-boost "$1"
	done

	exit 1
fi

echo "Invalid arguments" >&2
exit 1

